from __future__ import annotations

from enum import Enum

class Whitespace(Enum):
    Plus = ...
    Minus = ...
    Smart = ...
    Default = ...

class WhitespaceControl:
    @property
    def left(self) -> Whitespace: ...
    @property
    def right(self) -> Whitespace: ...

class Node:
    class Content:
        @property
        def text(self) -> str: ...

    class Output:
        @property
        def wc(self) -> WhitespaceControl: ...
        @property
        def expression(self) -> FilteredExpression: ...

    class Raw:
        @property
        def wc(self) -> tuple[WhitespaceControl, WhitespaceControl]: ...
        @property
        def text(self) -> str: ...

    class Comment:
        @property
        def wc(self) -> WhitespaceControl: ...
        @property
        def text(self) -> str: ...
        @property
        def hashes(self) -> str: ...

    class AssignTag:
        @property
        def wc(self) -> WhitespaceControl: ...
        @property
        def identifier(self) -> str: ...
        @property
        def expression(self) -> FilteredExpression: ...

    class CaptureTag:
        @property
        def wc(self) -> tuple[WhitespaceControl, WhitespaceControl]: ...
        @property
        def identifier(self) -> str: ...
        @property
        def block(self) -> list[Node]: ...

    class CaseTag:
        @property
        def wc(self) -> tuple[WhitespaceControl, WhitespaceControl]: ...
        @property
        def arg(self) -> Primitive: ...
        @property
        def whens(self) -> list[WhenTag]: ...
        @property
        def default(self) -> list[ElseTag]: ...

    class CycleTag:
        @property
        def wc(self) -> WhitespaceControl: ...
        @property
        def name(self) -> None | str: ...
        @property
        def args(self) -> list[Primitive]: ...

    class DecrementTag:
        @property
        def wc(self) -> WhitespaceControl: ...
        @property
        def name(self) -> str: ...

    class IncrementTag:
        @property
        def wc(self) -> WhitespaceControl: ...
        @property
        def name(self) -> str: ...

    class EchoTag:
        @property
        def wc(self) -> WhitespaceControl: ...
        @property
        def expression(self) -> FilteredExpression: ...

    class ForTag:
        @property
        def wc(self) -> tuple[WhitespaceControl, WhitespaceControl]: ...
        @property
        def name(self) -> str: ...
        @property
        def iterable(self) -> Primitive: ...
        @property
        def limit(self) -> None | Primitive: ...
        @property
        def offset(self) -> None | Primitive: ...
        @property
        def reversed(self) -> bool: ...
        @property
        def block(self) -> list[Node]: ...
        @property
        def default(self) -> None | ElseTag: ...

    class BreakTag:
        @property
        def wc(self) -> WhitespaceControl: ...

    class ContinueTag:
        @property
        def wc(self) -> WhitespaceControl: ...

    class IfTag:
        @property
        def wc(self) -> tuple[WhitespaceControl, WhitespaceControl]: ...
        @property
        def condition(self) -> BooleanExpression: ...
        @property
        def block(self) -> list[Node]: ...
        @property
        def alternatives(self) -> list[ElsifTag]: ...
        @property
        def default(self) -> None | ElseTag: ...

    class UnlessTag:
        @property
        def wc(self) -> tuple[WhitespaceControl, WhitespaceControl]: ...
        @property
        def condition(self) -> BooleanExpression: ...
        @property
        def block(self) -> list[Node]: ...
        @property
        def alternatives(self) -> list[ElsifTag]: ...
        @property
        def default(self) -> None | ElseTag: ...

    class IncludeTag:
        @property
        def wc(self) -> WhitespaceControl: ...
        @property
        def target(self) -> Primitive: ...
        @property
        def repeat(self) -> bool: ...
        @property
        def variable(self) -> None | Primitive: ...
        @property
        def alias(self) -> None | str: ...
        @property
        def args(self) -> None | list[CommonArgument]: ...

    class RenderTag:
        @property
        def wc(self) -> WhitespaceControl: ...
        @property
        def target(self) -> Primitive: ...
        @property
        def repeat(self) -> bool: ...
        @property
        def variable(self) -> None | Primitive: ...
        @property
        def alias(self) -> None | str: ...
        @property
        def args(self) -> None | list[CommonArgument]: ...

    class LiquidTag:
        @property
        def wc(self) -> WhitespaceControl: ...
        @property
        def block(self) -> list[Node]: ...

    class TagExtension:
        @property
        def wc(self) -> tuple[WhitespaceControl, None | WhitespaceControl]: ...
        @property
        def name(self) -> str: ...
        @property
        def args(self) -> list[CommonArgument]: ...
        @property
        def block(self) -> None | list[Node]: ...
        @property
        def tags(self) -> None | list[Node]: ...

class FilteredExpression:
    @property
    def left(self) -> Primitive: ...
    @property
    def filters(self) -> None | list[Filter]: ...
    @property
    def condition(self) -> None | InlineCondition: ...

class Filter:
    @property
    def name(self) -> str: ...
    @property
    def args(self) -> None | list[CommonArgument]: ...

class CommonArgument:
    @property
    def value(self) -> None | Primitive: ...
    @property
    def name(self) -> None | str: ...

class InlineCondition:
    @property
    def expr(self) -> BooleanExpression: ...
    @property
    def alternative(self) -> None | Primitive: ...
    @property
    def alternative_filters(self) -> None | list[Filter]: ...
    @property
    def tail_filters(self) -> None | list[Filter]: ...

class BooleanExpression:
    class Primitive:
        @property
        def expr(self) -> Primitive: ...

    class LogicalNot:
        @property
        def expr(self) -> BooleanExpression: ...

    class Logical:
        @property
        def left(self) -> BooleanExpression: ...
        @property
        def operator(self) -> BooleanOperator: ...
        @property
        def right(self) -> BooleanExpression: ...

    class Comparison:
        @property
        def left(self) -> BooleanExpression: ...
        @property
        def operator(self) -> ComparisonOperator: ...
        @property
        def right(self) -> BooleanExpression: ...

    class Membership:
        @property
        def left(self) -> BooleanExpression: ...
        @property
        def operator(self) -> MembershipOperator: ...
        @property
        def right(self) -> BooleanExpression: ...

class ElseTag:
    @property
    def wc(self) -> WhitespaceControl: ...
    @property
    def block(self) -> list[Node]: ...

class ElsifTag:
    @property
    def wc(self) -> WhitespaceControl: ...
    @property
    def condition(self) -> BooleanExpression: ...
    @property
    def block(self) -> list[Node]: ...

class WhenTag:
    @property
    def wc(self) -> WhitespaceControl: ...
    @property
    def args(self) -> list[Primitive]: ...
    @property
    def block(self) -> list[Node]: ...

class BooleanOperator(Enum):
    And = ...
    Or = ...

class ComparisonOperator(Enum):
    Eq = ...
    Ne = ...
    Ge = ...
    Gt = ...
    Le = ...
    Lt = ...

class MembershipOperator(Enum):
    In = ...
    NotIn = ...
    Contains = ...
    NotContains = ...

class Primitive:
    class TrueLiteral: ...
    class FalseLiteral: ...
    class NullLiteral: ...

    class Integer:
        @property
        def value(self) -> int: ...

    class Float:
        @property
        def value(self) -> float: ...

    class StringLiteral:
        @property
        def value(self) -> str: ...

    class Range:
        @property
        def start(self) -> int: ...
        @property
        def stop(self) -> int: ...

    class Query:
        @property
        def path(self) -> Query: ...

class Template:
    @property
    def liquid(self) -> list[Node]: ...

class ComparisonOp(Enum):
    Eq = ...
    Ne = ...
    Ge = ...
    Gt = ...
    Le = ...
    Lt = ...

class LogicalOp(Enum):
    And = ...
    Or = ...

class FilterExpression:
    class True_: ...
    class False_: ...
    class Null: ...

    class String:
        @property
        def value(self) -> str: ...

    class Int:
        @property
        def value(self) -> int: ...

    class Float:
        @property
        def value(self) -> float: ...

    class Not:
        @property
        def expression(self) -> FilterExpression_: ...

    class Logical:
        @property
        def left(self) -> FilterExpression_: ...
        @property
        def operator(self) -> LogicalOp: ...
        @property
        def right(self) -> FilterExpression_: ...

    class Comparison:
        @property
        def left(self) -> FilterExpression_: ...
        @property
        def operator(self) -> ComparisonOp: ...
        @property
        def right(self) -> FilterExpression_: ...

    class RelativeQuery:
        @property
        def query(self) -> Query: ...

    class RootQuery:
        @property
        def query(self) -> Query: ...

    class Function:
        @property
        def name(self) -> str: ...
        @property
        def args(self) -> list[FilterExpression_]: ...

FilterExpression_ = (
    FilterExpression.True_
    | FilterExpression.False_
    | FilterExpression.Null
    | FilterExpression.String
    | FilterExpression.Int
    | FilterExpression.Float
    | FilterExpression.Not
    | FilterExpression.Logical
    | FilterExpression.Comparison
    | FilterExpression.RelativeQuery
    | FilterExpression.RootQuery
    | FilterExpression.Function
)

class Selector:
    class Name:
        @property
        def name(self) -> str: ...

    class Index:
        @property
        def index(self) -> int: ...

    class Slice:
        @property
        def start(self) -> int | None: ...
        @property
        def stop(self) -> int | None: ...
        @property
        def step(self) -> int | None: ...

    class Wild: ...

    class Filter:
        @property
        def expression(self) -> FilterExpression_: ...

Selector_ = (
    Selector.Name | Selector.Index | Selector.Slice | Selector.Wild | Selector.Filter
)

SelectorList = list[Selector_]

class Segment:
    class Child:
        __match_args__ = ("selectors", "span")
        @property
        def selectors(self) -> SelectorList: ...

    class Recursive:
        __match_args__ = ("selectors", "span")
        @property
        def selectors(self) -> SelectorList: ...

class Query:
    @property
    def segments(self) -> list[Segment.Child | Segment.Recursive]: ...

def parse(source: str) -> Template: ...
